# Configurações Principais do Servidor
server_name = Terras Abertas Oficial
server_description = O servidor oficial do jogo Terras Abertas! Entre e sobreviva.
server_address = 0.0.0.0
port = 30000

# Mensagem que aparece no chat quando o jogador entra
motd = Bem-vindo ao Terras Abertas! Divirta-se criando e sobrevivendo.

# Privilégios que TODO jogador ganha ao entrar pela primeira vez
# (shout permite falar no chat, interact permite quebrar/colocar blocos)
default_privs = shout, interact

# Segurança e Moderação
max_users = 10
disallow_empty_password = true

# Otimização para o Render (Evita travamentos na nuvem gratuita)
max_block_send_distance = 6
max_block_generate_distance = 4
active_block_range = 1
